/** [dialCode, flag, country] – Italia first, then alphabetical */
export const PREFIXES: [string, string, string][] = [
  ['+39',  '🇮🇹', 'Italia'],
  ['+93',  '🇦🇫', 'Afghanistan'],
  ['+355', '🇦🇱', 'Albania'],
  ['+213', '🇩🇿', 'Algeria'],
  ['+376', '🇦🇩', 'Andorra'],
  ['+244', '🇦🇴', 'Angola'],
  ['+1268','🇦🇬', 'Antigua e Barbuda'],
  ['+966', '🇸🇦', 'Arabia Saudita'],
  ['+54',  '🇦🇷', 'Argentina'],
  ['+374', '🇦🇲', 'Armenia'],
  ['+61',  '🇦🇺', 'Australia'],
  ['+43',  '🇦🇹', 'Austria'],
  ['+994', '🇦🇿', 'Azerbaigian'],
  ['+1242','🇧🇸', 'Bahamas'],
  ['+973', '🇧🇭', 'Bahrain'],
  ['+880', '🇧🇩', 'Bangladesh'],
  ['+1246','🇧🇧', 'Barbados'],
  ['+32',  '🇧🇪', 'Belgio'],
  ['+501', '🇧🇿', 'Belize'],
  ['+229', '🇧🇯', 'Benin'],
  ['+975', '🇧🇹', 'Bhutan'],
  ['+375', '🇧🇾', 'Bielorussia'],
  ['+591', '🇧🇴', 'Bolivia'],
  ['+387', '🇧🇦', 'Bosnia ed Erzegovina'],
  ['+267', '🇧🇼', 'Botswana'],
  ['+55',  '🇧🇷', 'Brasile'],
  ['+673', '🇧🇳', 'Brunei'],
  ['+359', '🇧🇬', 'Bulgaria'],
  ['+226', '🇧🇫', 'Burkina Faso'],
  ['+257', '🇧🇮', 'Burundi'],
  ['+238', '🇨🇻', 'Cabo Verde'],
  ['+855', '🇰🇭', 'Cambogia'],
  ['+237', '🇨🇲', 'Camerun'],
  ['+1',   '🇨🇦', 'Canada'],
  ['+235', '🇹🇩', 'Ciad'],
  ['+56',  '🇨🇱', 'Cile'],
  ['+86',  '🇨🇳', 'Cina'],
  ['+357', '🇨🇾', 'Cipro'],
  ['+57',  '🇨🇴', 'Colombia'],
  ['+269', '🇰🇲', 'Comore'],
  ['+242', '🇨🇬', 'Congo (Rep.)'],
  ['+243', '🇨🇩', 'Congo (Rep. Dem.)'],
  ['+850', '🇰🇵', 'Corea del Nord'],
  ['+82',  '🇰🇷', 'Corea del Sud'],
  ['+225', '🇨🇮', "Costa d'Avorio"],
  ['+506', '🇨🇷', 'Costa Rica'],
  ['+385', '🇭🇷', 'Croazia'],
  ['+53',  '🇨🇺', 'Cuba'],
  ['+45',  '🇩🇰', 'Danimarca'],
  ['+1767','🇩🇲', 'Dominica'],
  ['+593', '🇪🇨', 'Ecuador'],
  ['+20',  '🇪🇬', 'Egitto'],
  ['+503', '🇸🇻', 'El Salvador'],
  ['+971', '🇦🇪', 'Emirati Arabi Uniti'],
  ['+291', '🇪🇷', 'Eritrea'],
  ['+372', '🇪🇪', 'Estonia'],
  ['+268', '🇸🇿', 'Eswatini'],
  ['+251', '🇪🇹', 'Etiopia'],
  ['+679', '🇫🇯', 'Figi'],
  ['+63',  '🇵🇭', 'Filippine'],
  ['+358', '🇫🇮', 'Finlandia'],
  ['+33',  '🇫🇷', 'Francia'],
  ['+241', '🇬🇦', 'Gabon'],
  ['+220', '🇬🇲', 'Gambia'],
  ['+995', '🇬🇪', 'Georgia'],
  ['+49',  '🇩🇪', 'Germania'],
  ['+233', '🇬🇭', 'Ghana'],
  ['+1876','🇯🇲', 'Giamaica'],
  ['+81',  '🇯🇵', 'Giappone'],
  ['+253', '🇩🇯', 'Gibuti'],
  ['+962', '🇯🇴', 'Giordania'],
  ['+30',  '🇬🇷', 'Grecia'],
  ['+1473','🇬🇩', 'Grenada'],
  ['+502', '🇬🇹', 'Guatemala'],
  ['+224', '🇬🇳', 'Guinea'],
  ['+240', '🇬🇶', 'Guinea Equatoriale'],
  ['+245', '🇬🇼', 'Guinea-Bissau'],
  ['+592', '🇬🇾', 'Guyana'],
  ['+509', '🇭🇹', 'Haiti'],
  ['+504', '🇭🇳', 'Honduras'],
  ['+852', '🇭🇰', 'Hong Kong'],
  ['+91',  '🇮🇳', 'India'],
  ['+62',  '🇮🇩', 'Indonesia'],
  ['+98',  '🇮🇷', 'Iran'],
  ['+964', '🇮🇶', 'Iraq'],
  ['+353', '🇮🇪', 'Irlanda'],
  ['+354', '🇮🇸', 'Islanda'],
  ['+692', '🇲🇭', 'Isole Marshall'],
  ['+677', '🇸🇧', 'Isole Salomone'],
  ['+972', '🇮🇱', 'Israele'],
  ['+7',   '🇰🇿', 'Kazakhstan'],
  ['+254', '🇰🇪', 'Kenya'],
  ['+996', '🇰🇬', 'Kirghizistan'],
  ['+686', '🇰🇮', 'Kiribati'],
  ['+383', '🇽🇰', 'Kosovo'],
  ['+965', '🇰🇼', 'Kuwait'],
  ['+856', '🇱🇦', 'Laos'],
  ['+266', '🇱🇸', 'Lesotho'],
  ['+371', '🇱🇻', 'Lettonia'],
  ['+961', '🇱🇧', 'Libano'],
  ['+231', '🇱🇷', 'Liberia'],
  ['+218', '🇱🇾', 'Libia'],
  ['+423', '🇱🇮', 'Liechtenstein'],
  ['+370', '🇱🇹', 'Lituania'],
  ['+352', '🇱🇺', 'Lussemburgo'],
  ['+853', '🇲🇴', 'Macao'],
  ['+389', '🇲🇰', 'Macedonia del Nord'],
  ['+261', '🇲🇬', 'Madagascar'],
  ['+265', '🇲🇼', 'Malawi'],
  ['+60',  '🇲🇾', 'Malaysia'],
  ['+960', '🇲🇻', 'Maldive'],
  ['+223', '🇲🇱', 'Mali'],
  ['+356', '🇲🇹', 'Malta'],
  ['+212', '🇲🇦', 'Marocco'],
  ['+222', '🇲🇷', 'Mauritania'],
  ['+230', '🇲🇺', 'Mauritius'],
  ['+52',  '🇲🇽', 'Messico'],
  ['+691', '🇫🇲', 'Micronesia'],
  ['+373', '🇲🇩', 'Moldova'],
  ['+377', '🇲🇨', 'Monaco'],
  ['+976', '🇲🇳', 'Mongolia'],
  ['+382', '🇲🇪', 'Montenegro'],
  ['+258', '🇲🇿', 'Mozambico'],
  ['+95',  '🇲🇲', 'Myanmar'],
  ['+264', '🇳🇦', 'Namibia'],
  ['+674', '🇳🇷', 'Nauru'],
  ['+977', '🇳🇵', 'Nepal'],
  ['+505', '🇳🇮', 'Nicaragua'],
  ['+227', '🇳🇪', 'Niger'],
  ['+234', '🇳🇬', 'Nigeria'],
  ['+47',  '🇳🇴', 'Norvegia'],
  ['+64',  '🇳🇿', 'Nuova Zelanda'],
  ['+968', '🇴🇲', 'Oman'],
  ['+31',  '🇳🇱', 'Paesi Bassi'],
  ['+92',  '🇵🇰', 'Pakistan'],
  ['+680', '🇵🇼', 'Palau'],
  ['+970', '🇵🇸', 'Palestina'],
  ['+507', '🇵🇦', 'Panama'],
  ['+675', '🇵🇬', 'Papua Nuova Guinea'],
  ['+595', '🇵🇾', 'Paraguay'],
  ['+51',  '🇵🇪', 'Perù'],
  ['+48',  '🇵🇱', 'Polonia'],
  ['+351', '🇵🇹', 'Portogallo'],
  ['+974', '🇶🇦', 'Qatar'],
  ['+44',  '🇬🇧', 'Regno Unito'],
  ['+420', '🇨🇿', 'Rep. Ceca'],
  ['+236', '🇨🇫', 'Rep. Centrafricana'],
  ['+1809','🇩🇴', 'Rep. Dominicana'],
  ['+40',  '🇷🇴', 'Romania'],
  ['+250', '🇷🇼', 'Ruanda'],
  ['+7',   '🇷🇺', 'Russia'],
  ['+1869','🇰🇳', 'Saint Kitts e Nevis'],
  ['+1758','🇱🇨', 'Saint Lucia'],
  ['+1784','🇻🇨', 'Saint Vincent e Grenadine'],
  ['+685', '🇼🇸', 'Samoa'],
  ['+378', '🇸🇲', 'San Marino'],
  ['+239', '🇸🇹', 'São Tomé e Príncipe'],
  ['+221', '🇸🇳', 'Senegal'],
  ['+381', '🇷🇸', 'Serbia'],
  ['+248', '🇸🇨', 'Seychelles'],
  ['+232', '🇸🇱', 'Sierra Leone'],
  ['+65',  '🇸🇬', 'Singapore'],
  ['+963', '🇸🇾', 'Siria'],
  ['+421', '🇸🇰', 'Slovacchia'],
  ['+386', '🇸🇮', 'Slovenia'],
  ['+252', '🇸🇴', 'Somalia'],
  ['+34',  '🇪🇸', 'Spagna'],
  ['+94',  '🇱🇰', 'Sri Lanka'],
  ['+1',   '🇺🇸', 'Stati Uniti'],
  ['+27',  '🇿🇦', 'Sud Africa'],
  ['+249', '🇸🇩', 'Sudan'],
  ['+211', '🇸🇸', 'Sudan del Sud'],
  ['+597', '🇸🇷', 'Suriname'],
  ['+46',  '🇸🇪', 'Svezia'],
  ['+41',  '🇨🇭', 'Svizzera'],
  ['+992', '🇹🇯', 'Tagikistan'],
  ['+886', '🇹🇼', 'Taiwan'],
  ['+255', '🇹🇿', 'Tanzania'],
  ['+66',  '🇹🇭', 'Thailandia'],
  ['+670', '🇹🇱', 'Timor Est'],
  ['+228', '🇹🇬', 'Togo'],
  ['+676', '🇹🇴', 'Tonga'],
  ['+1868','🇹🇹', 'Trinidad e Tobago'],
  ['+216', '🇹🇳', 'Tunisia'],
  ['+90',  '🇹🇷', 'Turchia'],
  ['+993', '🇹🇲', 'Turkmenistan'],
  ['+688', '🇹🇻', 'Tuvalu'],
  ['+380', '🇺🇦', 'Ucraina'],
  ['+256', '🇺🇬', 'Uganda'],
  ['+36',  '🇭🇺', 'Ungheria'],
  ['+598', '🇺🇾', 'Uruguay'],
  ['+998', '🇺🇿', 'Uzbekistan'],
  ['+678', '🇻🇺', 'Vanuatu'],
  ['+58',  '🇻🇪', 'Venezuela'],
  ['+84',  '🇻🇳', 'Vietnam'],
  ['+967', '🇾🇪', 'Yemen'],
  ['+260', '🇿🇲', 'Zambia'],
  ['+263', '🇿🇼', 'Zimbabwe'],
];
